# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_main_add
#'
#' @noRd
rcpp_main_add <- function(vec) {
    .Call(`_subdirtest_rcpp_main_add`, vec)
}

